const edge = { TOP:[50,0], RIGHT:[100,50], BOTTOM:[50,100], LEFT:[0,50] };
const pivots = [[50,50], [61,39], [39,61], [61,61]];
const rockSpecks = [[15,16,3],[82,17,4],[19,78,4],[80,80,3],[33,28,2],[70,68,2]];

export function PathIcon({ connections=[], routes, goal=false, treasure=false, revealed=false }) {
  if (goal) return <svg className={`goal-card ${revealed ? 'revealed' : ''} ${treasure ? 'treasure' : 'rock-goal'}`} viewBox="0 0 100 100" aria-hidden="true"><rect className="mine-card-base" x="2" y="2" width="96" height="96" rx="11"/><path className="rock" d="M16 61 27 25 57 12 84 31 89 67 65 89 28 83Z"/><text x="50" y="61" textAnchor="middle">{revealed ? (treasure ? '◆' : '×') : '?'}</text></svg>;
  const tunnelRoutes = routes || [connections];
  return <svg viewBox="0 0 100 100" aria-hidden="true"><rect className="mine-card-base" x="2" y="2" width="96" height="96" rx="11"/><rect className="earth" x="6" y="6" width="88" height="88" rx="8"/>{rockSpecks.map(([cx,cy,r], index) => <circle className="ore-speck" key={index} cx={cx} cy={cy} r={r}/>)}{tunnelRoutes.map((route, index) => { const pivot = tunnelRoutes.length === 1 ? [50,50] : pivots[index % pivots.length]; const routePoints = route.length === 1 ? [edge[route[0]], pivot] : route.flatMap((direction, routeIndex) => routeIndex ? [pivot, edge[direction]] : [edge[direction]]); return <g key={`${index}-${route.join('-')}`}><polyline className="tunnel-shadow" fill="none" points={routePoints.map(point => point.join(',')).join(' ')}/><polyline className="tunnel" fill="none" points={routePoints.map(point => point.join(',')).join(' ')}/>{route.length === 1 && <circle className="dead-end" cx={pivot[0]} cy={pivot[1]} r="9"/>}{route.length > 2 && <circle className="hub" cx={pivot[0]} cy={pivot[1]} r="11"/>}</g>; })}</svg>;
}
